azd env set AZURE_RESOURCE_GROUP rg-Magi-Water
azd env set AZURE_OPENAI_SERVICE cog-magi-4vision
azd env set AZURE_OPENAI_RESOURCE_GROUP rg-Magi-Knowledge
azd env set AZURE_OPENAI_CHAT_DEPLOYMENT Chat4-Turbo
azd env set AZURE_OPENAI_CHATGPT_MODEL gpt-4
azd env set AZURE_OPENAI_GPT4V_MODEL gpt-4
azd env set AZURE_OPENAI_GPT4V_DEPLOYMENT Chat-Vision
azd env set AZURE_OPENAI_EMB_DEPLOYMENT text
azd env set AZURE_OPENAI_EMB_MODEL_NAME text-embedding-ada-002
azd env set AZURE_SEARCH_SERVICE gptkb-54xej7v56bd5e
azd env set AZURE_SEARCH_SERVICE_RESOURCE_GROUP rg-Magi-Knowledge
azd env set AZURE_OPENAI_SERVICE_LOCATION swedencentral
azd env set AZURE_SEARCH_INDEX gptwateryindex
azd env set AZURE_DOCUMENTINTELLIGENCE_SERVICE cog-di-5t2dl7rbqegwc
azd env set AZURE_DOCUMENTINTELLIGENCE_LOCATION westeurope
azd env set AZURE_DOCUMENTINTELLIGENCE_RESOURCE_GROUP rg-Magi-Knowledge
azd env set AZURE_STORAGE_ACCOUNT st54xej7v56bd5e
azd env set AZURE_STORAGE_RESOURCE_GROUP rg-Magi-Knowledge
azd env set AZURE_STORAGE_CONTAINER watercontent
azd env set USE_FEATURE_INT_VECTORIZATION false
azd env set USE_GPT4V true
azd env set AZURE_SUBSCRIPTION_ID 7bc1a556-89ac-4228-886a-8d72b4d090eb
